### ISSUE TITLE
SAAS Website - Revised Sketches

### ISSUE THREAD

**Issue by LauraWilson040** [LauraWilson040/saas-website#1]
![wilson-laura-4-saas-website-index](https://user-images.githubusercontent.com/55108851/79043583-04122980-7bce-11ea-8442-1d873eb331cf.jpg)
![wilson-laura-4-saas-website-signup](https://user-images.githubusercontent.com/55108851/79043584-05dbed00-7bce-11ea-8aec-abd8b0b39f55.jpg)
![wilson-laura-4-saas-website-tour](https://user-images.githubusercontent.com/55108851/79043587-07a5b080-7bce-11ea-8382-d40d60e42608.jpg)

@muxlowc

**Comment by muxlowc** [comment]
@LauraWilson040 looks great!
